baseURL: "https://github.com/adashiyj/personal-website/blob/main/config.yml" 
title: Ada Shi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

menu:
    main:
        - name: About Me
          url: aboutme/
          weight: 1 
        - name: Projects
          url: projects/
          weight: 2

params:
    description: "This website hosts Ada Shi's curriculum vitae, contact information, projects, and blogs."
    author: Ada Shi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["aboutme","projects"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ada Shi
          subtitle: "Hi there! Welcome to my website. I'm a research master's student in Communication Science at the University of Amsterdam. My research focuses on social robotics and human machine communication."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: aboutme/
            - name: Projects
              url: projects/

    socialIcons:
        - name: Email
          url: mailto:adashiyj@gmail.com
        - name: GitHub
          url: https://github.com/adashiyj
        - name: Bluesky
          url: https://@adashiyj.bsky.social
        - name: LinkedIn
          url: https://www.linkedin.com/in/ada-yujia-s-495474251/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ada Shi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
